export const NEWSROOM_REQUEST = "NEWSROOM_REQUEST";
export const NEWSROOM_SUCCESS = "NEWSROOM_SUCCESS";
export const NEWSROOM_FAILURE = "NEWSROOM_FAILURE";

export const POST_NEWSROOM_REQUEST = "POST_NEWSROOM_REQUEST";
export const POST_NEWSROOM_SUCCESS = "POST_NEWSROOM_SUCCESS";
export const POST_NEWSROOM_FAILURE = "POST_NEWSROOM_FAILURE";

export const EDIT_NEWSROOM_REQUEST = "EDIT_NEWSROOM_REQUEST";
export const EDIT_NEWSROOM_SUCCESS = "EDIT_NEWSROOM_SUCCESS";
export const EDIT_NEWSROOM_FAILURE = "EDIT_NEWSROOM_FAILURE";

export const DELETE_NEWSROOM_REQUEST = "DELETE_NEWSROOM_REQUEST";
export const DELETE_NEWSROOM_SUCCESS = "DELETE_NEWSROOM_SUCCESS";
export const DELETE_NEWSROOM_FAILURE = "DELETE_NEWSROOM_FAILURE";
