export const SERVICE_REQUEST = "SERVICE_REQUEST";
export const SERVICE_SUCCESS = "SERVICE_SUCCESS";
export const SERVICE_FAILURE = "SERVICE_FAILURE";

export const POST_SERVICE_REQUEST = "POST_SERVICE_REQUEST";
export const POST_SERVICE_SUCCESS = "POST_SERVICE_SUCCESS";
export const POST_SERVICE_FAILURE = "POST_SERVICE_FAILURE";

export const EDIT_SERVICE_REQUEST = "EDIT_SERVICE_REQUEST";
export const EDIT_SERVICE_SUCCESS = "EDIT_SERVICE_SUCCESS";
export const EDIT_SERVICE_FAILURE = "EDIT_SERVICE_FAILURE";

export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAILURE = "DELETE_SERVICE_FAILURE";
