export const DISCOVER_REQUEST = "DISCOVER_REQUEST";
export const DISCOVER_SUCCESS = "DISCOVER_SUCCESS";
export const DISCOVER_FAILURE = "DISCOVER_FAILURE";

export const POST_DISCOVER_REQUEST = "POST_DISCOVER_REQUEST";
export const POST_DISCOVER_SUCCESS = "POST_DISCOVER_SUCCESS";
export const POST_DISCOVER_FAILURE = "POST_DISCOVER_FAILURE";

export const EDIT_DISCOVER_REQUEST = "EDIT_DISCOVER_REQUEST";
export const EDIT_DISCOVER_SUCCESS = "EDIT_DISCOVER_SUCCESS";
export const EDIT_DISCOVER_FAILURE = "EDIT_DISCOVER_FAILURE";

export const DELETE_DISOCOVER_REQUEST = "DELETE_DISOCOVER_REQUEST";
export const DELETE_DISOCOVER_SUCCESS = "DELETE_DISOCOVER_SUCCESS";
export const DELETE_DISOCOVER_FAILURE = "DELETE_DISOCOVER_FAILURE";